##################################################################################
# Cloudify Logstash Plugin.
##################################################################################

plugins:
  logstash:
    executor: central_deployment_agent
    source: https://github.com/EarthmanT/cloudify-logstash-plugin/archive/master.zip

node_types:

  logstash:
    derived_from: cloudify.nodes.ApplicationServer
    properties:
      package_source:
        default: {}
        description: >
          A URL to an rpm or .deb file that you will use to install the logstash service.
      config_source:
        default: {}
        description: >
          A file in the blueprint directory that contains the Logstash config.
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: logstash.logstash_plugin.tasks.install
          inputs:
            default:
              java_path: java
              package_source: { get_property: [ SELF, package_source ] }
        configure:
          implementation: logstash.logstash_plugin.tasks.configure
          inputs:
            default:
              config_source: { get_property: [ SELF, config_source ] }
        start:
          implementation: logstash.logstash_plugin.tasks.start
        stop:
          implementation: logstash.logstash_plugin.tasks.stop
