##################################################################################
# Cloudify Logstash Plugin.
##################################################################################

plugins:
  logstash:
    executor: central_deployment_agent
    source: https://github.com/cloudify-cosmo/cloudify-logstash-plugin/archive/1.2.zip

node_types:

  logstash:
    derived_from: cloudify.nodes.ApplicationServer
    properties:
      package_source:
        default: {}
        description: >
          A URL to an rpm or .deb file that you will use to install the logstash service.
      config_source:
        default: {}
        description: >
          A file in the blueprint directory that contains the Logstash config.
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: fabric.fabric_plugin.tasks.run_task
          inputs:
            tasks_file: logstash_plugin/tasks.py
            task_name: install
            task_properties:
              java_path: java
              package_source: { get_property: [ SELF, package_source ] }
        configure:
          implementation: fabric.fabric_plugin.tasks.run_task
          inputs:
            tasks_file: logstash_plugin/tasks.py
            task_name: configure
            task_properties:
              config_source: { get_property: [ SELF, config_source ] }
        start:
          implementation: fabric.fabric_plugin.tasks.run_task
          inputs:
            tasks_file: logstash_plugin/tasks.py
            task_name: start
        stop:
          implementation: fabric.fabric_plugin.tasks.run_task
          inputs:
            tasks_file: logstash_plugin/tasks.py
            task_name: stop
